// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDifUYLn0pMtuIbXxI3kkVn_-cZrSDCmIQ',
    appId: '1:167208167982:web:e186797da240b0ce09cdbf',
    messagingSenderId: '167208167982',
    projectId: 'planzy-5f572',
    authDomain: 'planzy-5f572.firebaseapp.com',
    storageBucket: 'planzy-5f572.firebasestorage.app',
    measurementId: 'G-C7LWK8XRZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXXrBkdV23mYwH9nU38LeGYM2rc2BoZ4',
    appId: '1:167208167982:android:c844147201858b8b09cdbf',
    messagingSenderId: '167208167982',
    projectId: 'planzy-5f572',
    storageBucket: 'planzy-5f572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr4EPTYJtIXq2ApHE5DhkbLplTBEY8xz8',
    appId: '1:167208167982:ios:730c740b7075bf6709cdbf',
    messagingSenderId: '167208167982',
    projectId: 'planzy-5f572',
    storageBucket: 'planzy-5f572.firebasestorage.app',
    iosBundleId: 'com.planzy.planzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr4EPTYJtIXq2ApHE5DhkbLplTBEY8xz8',
    appId: '1:167208167982:ios:730c740b7075bf6709cdbf',
    messagingSenderId: '167208167982',
    projectId: 'planzy-5f572',
    storageBucket: 'planzy-5f572.firebasestorage.app',
    iosBundleId: 'com.planzy.planzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDifUYLn0pMtuIbXxI3kkVn_-cZrSDCmIQ',
    appId: '1:167208167982:web:4f1f9d22e8dcfeb709cdbf',
    messagingSenderId: '167208167982',
    projectId: 'planzy-5f572',
    authDomain: 'planzy-5f572.firebaseapp.com',
    storageBucket: 'planzy-5f572.firebasestorage.app',
    measurementId: 'G-BPKGJW2DQN',
  );
}
